name: Fortify Scan

on:
  push:
    branches:
      - main  # Adjust to your default branch
  pull_request:
    branches:
      - main  # Adjust to your default branch

jobs:
  fortify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew      

      - name: Build with Gradle
        run: ./gradlew build

      - name: Download Fortify CLI
        run: |
          curl -LO https://your-fortify-server/fortify-cli/fortify-cli-linux-20.2.0.zip
          unzip fortify-cli-linux-20.2.0.zip
          sudo mv fortify-cli /usr/local/bin/fortify-cli

      - name: Run Fortify Scan
        run: |
          fortify-cli translate -b build/ -f source.fpr -scan -project "Java_App" -version "1.0" -url ${{ secrets.FORTIFY_SERVER }} -token ${{ secrets.FOD_PAT}}

      - name: Upload Fortify Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: fortify-results
          path: |
            source.fpr
